# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_scherduler.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17server_scherduler.proto\x12\x07\x63ommand\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"6\n\x0f\x43ommandResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\"6\n\x10SchedulerRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"8\n\x11SchedulerResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x32V\n\x0f\x43ommandExecutor\x12\x43\n\x0e\x45xecuteCommand\x12\x17.command.CommandRequest\x1a\x18.command.CommandResponse2U\n\tScheduler\x12H\n\x0fScheduleCommand\x12\x19.command.SchedulerRequest\x1a\x1a.command.SchedulerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_scherduler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMANDREQUEST']._serialized_start=36
  _globals['_COMMANDREQUEST']._serialized_end=69
  _globals['_COMMANDRESPONSE']._serialized_start=71
  _globals['_COMMANDRESPONSE']._serialized_end=125
  _globals['_SCHEDULERREQUEST']._serialized_start=127
  _globals['_SCHEDULERREQUEST']._serialized_end=181
  _globals['_SCHEDULERRESPONSE']._serialized_start=183
  _globals['_SCHEDULERRESPONSE']._serialized_end=239
  _globals['_COMMANDEXECUTOR']._serialized_start=241
  _globals['_COMMANDEXECUTOR']._serialized_end=327
  _globals['_SCHEDULER']._serialized_start=329
  _globals['_SCHEDULER']._serialized_end=414
# @@protoc_insertion_point(module_scope)
