# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_tool import server_scherduler_pb2 as server__scherduler__pb2


class CommandExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCommand = channel.unary_unary(
                '/command.CommandExecutor/ExecuteCommand',
                request_serializer=server__scherduler__pb2.CommandRequest.SerializeToString,
                response_deserializer=server__scherduler__pb2.CommandResponse.FromString,
                )


class CommandExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=server__scherduler__pb2.CommandRequest.FromString,
                    response_serializer=server__scherduler__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'command.CommandExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommandExecutor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/command.CommandExecutor/ExecuteCommand',
            server__scherduler__pb2.CommandRequest.SerializeToString,
            server__scherduler__pb2.CommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SchedulerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScheduleCommand = channel.unary_unary(
                '/command.Scheduler/ScheduleCommand',
                request_serializer=server__scherduler__pb2.SchedulerRequest.SerializeToString,
                response_deserializer=server__scherduler__pb2.SchedulerResponse.FromString,
                )


class SchedulerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScheduleCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScheduleCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleCommand,
                    request_deserializer=server__scherduler__pb2.SchedulerRequest.FromString,
                    response_serializer=server__scherduler__pb2.SchedulerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'command.Scheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scheduler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScheduleCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/command.Scheduler/ScheduleCommand',
            server__scherduler__pb2.SchedulerRequest.SerializeToString,
            server__scherduler__pb2.SchedulerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
